---
title: "Call Stack and Conditions in R"
date: 2020-09-01
author: Nick Griffiths
categories: Programming
---

<script src="/rmarkdown-libs/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(rlang)
library(lobstr)</code></pre>
<p>This is a cheatsheet outlining the basics of the call stack and condition handling system in R. The <a href="https://adv-r.hadley.nz/">Advanced R</a> book has lots more detail.</p>
<div id="environments" class="section level3">
<h3>1. Environments</h3>
<p>Print the current environment:</p>
<pre class="r"><code>env_print(current_env())
#&gt; &lt;environment: global&gt;
#&gt; parent: &lt;environment: package:lobstr&gt;

env_print(environment())
#&gt; &lt;environment: global&gt;
#&gt; parent: &lt;environment: package:lobstr&gt;</code></pre>
<p>Print the caller environment:</p>
<pre class="r"><code>f &lt;- function () env_print(caller_env())
f &lt;- function () env_print(parent.frame())
f()
#&gt; &lt;environment: global&gt;
#&gt; parent: &lt;environment: package:lobstr&gt;
#&gt; bindings:
#&gt;  * f: &lt;fn&gt;</code></pre>
</div>
<div id="traces" class="section level3">
<h3>2. Traces</h3>
<p>Print the trace:</p>
<pre class="r"><code>f &lt;- function () stop(&quot;test&quot;)
f()
#&gt; Error in f() : test
traceback()
#&gt; 2: stop(&quot;test&quot;) at #1
#&gt; 1: f()</code></pre>
<p>Traces are stored in <code>.Traceback</code> in base R. <code>rlang::abort()</code> stores its traces in its own environment (<code>rlang:::last_error_env</code>).</p>
<p>Because arguments are evaluated lazily, the (linear) call stack can have a branching environment structure. In other words, several frames on the call stack can be children of the same environment. This is displayed in <code>rlang</code> traces.</p>
<p>In this example, <code>i()</code> is called after <code>h()</code> but its evaluation context is a child of the global environment (clearly it can’t reference anything in the body of <code>h()</code>).</p>
<pre class="r"><code>i &lt;- function () { 
  lobstr::cst()
}

h &lt;- function (x) x   # x is evaluated, calling i()

g &lt;- function (x) h(x)  # x isn&#39;t touched

f &lt;- function (x) g(x)  # x isn&#39;t touched

g(i())
#&gt;     █
#&gt;  1. ├─global::g(i())
#&gt;  2. │ └─global::h(x)
#&gt;  3. └─global::i()
#&gt;  4.   └─lobstr::cst()</code></pre>
</div>
<div id="conditions" class="section level3">
<h3>3. Conditions</h3>
<p>Any signalled conditions are handled by the handler stack. The stack is made up of two kinds of handlers, exiting and local. Each call to <code>tryCatch()</code> or <code>withCallingHandlers()</code> adds to both the handler stack and the callstack, but the two stacks behave a bit differently.</p>
<p><code>tryCatch()</code> establishes exiting handlers:</p>
<pre class="r"><code>g &lt;- function () stop(&quot;stopping&quot;)
f &lt;- function () g()

tryCatch(f(), error = function (x) {
  cat(&quot;\nR throws away everything deeper than tryCatch:\n&quot;)
  lobstr::cst()
  cat(&quot;\nthis is the caller&#39;s environment (tryCatchOne&#39;s env):\n&quot;)
  env_print(parent.frame(1))
  cat(&quot;\nbut tryCatch knows the function where the error actually occurred:\n&quot;)
  print(get(&quot;call&quot;, parent.frame()))
  cat(&quot;\n&quot;)
  &quot;handler value gets returned&quot;
})
#&gt; 
#&gt; R throws away everything deeper than tryCatch:
#&gt;     █
#&gt;  1. └─base::tryCatch(...)
#&gt;  2.   └─base:::tryCatchList(expr, classes, parentenv, handlers)
#&gt;  3.     └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
#&gt;  4.       └─value[[3L]](cond)
#&gt;  5.         └─lobstr::cst()
#&gt; 
#&gt; this is the caller&#39;s environment (tryCatchOne&#39;s env):
#&gt; &lt;environment: 0x7fbbc83bbeb0&gt;
#&gt; parent: &lt;environment: 0x7fbbc83bc8f8&gt;
#&gt; bindings:
#&gt;  * cond: &lt;smplErrr&gt;
#&gt;  * call: &lt;language&gt;
#&gt;  * msg: &lt;chr&gt;
#&gt;  * value: &lt;list&gt;
#&gt;  * doTryCatch: &lt;fn&gt;
#&gt;  * expr: &lt;lazy&gt;
#&gt;  * name: &lt;chr&gt;
#&gt;  * parentenv: &lt;env&gt;
#&gt;  * handler: &lt;fn&gt;
#&gt; 
#&gt; but tryCatch knows the function where the error actually occurred:
#&gt; g()
#&gt; [1] &quot;handler value gets returned&quot;</code></pre>
<p><code>withCallingHandlers()</code> establishes local handlers:</p>
<pre class="r"><code>g &lt;- function () {
  stop(&quot;stopping&quot;)
}

f &lt;- function () {
  g()
}

secondLobstr &lt;- lobstr::cst

withCallingHandlers(f(), error = function (x) {
  cat(&quot;\nThree-stage execution restarting from global each time:\n&quot;)
  lobstr::cst()
  cat(&quot;\nthis is the caller&#39;s environment (.handleSimpleError&#39;s env):\n&quot;)
  env_print(parent.frame())
  &quot;the return val is discarded&quot;
}, error = function (x) {
  cat(&quot;\nThis is handler #2\n&quot;)
  cat(&quot;\nNote the identical call stack to handler #1\n&quot;)
  secondLobstr()
  invokeRestart(&quot;abort&quot;)
})
#&gt; Three-stage execution restarting from global each time:
#&gt;    █
#&gt; 1. ├─base::withCallingHandlers(...)
#&gt; 2. ├─global::f()
#&gt; 3. │ └─global::g()
#&gt; 4. │   └─base::stop(&quot;stopping&quot;)
#&gt; 5. └─base::.handleSimpleError(...)
#&gt; 6.   └─global::h(simpleError(msg, call))
#&gt; 7.     └─lobstr::cst()
#&gt;
#&gt; this is the caller&#39;s environment (.handleSimpleError&#39;s env):
#&gt; &lt;environment: 0x7f8743386b28&gt;
#&gt; parent: &lt;environment: namespace:base&gt;
#&gt; bindings:
#&gt;  * h: &lt;fn&gt;
#&gt;  * msg: &lt;lazy&gt;
#&gt;  * call: &lt;lazy&gt;
#&gt; 
#&gt; This is handler #2
#&gt; 
#&gt; Note the identical call stack to handler #1
#&gt;     █
#&gt;  1. ├─base::withCallingHandlers(...)
#&gt;  2. ├─global::f()
#&gt;  3. │ └─global::g()
#&gt;  4. │   └─base::stop(&quot;stopping&quot;)
#&gt;  5. └─base::.handleSimpleError(...)
#&gt;  6.   └─global::h(simpleError(msg, call))
#&gt;  7.     └─lobstr:::secondLobstr()</code></pre>
<p>Important rules of condition handling:</p>
<ol style="list-style-type: decimal">
<li><p>R looks for handlers in the handler stack from the top down (most recently added to least recent). Inside one <code>withCallingHandlers()</code> call, the first handler is considered the topmost handler (most recent). Local handlers are called, if they exist, before exiting handlers.</p></li>
<li><p>Once a handler has been called, the only valid handlers left are those lower in the handler stack (less recent).</p></li>
<li><p>When invoking an exiting handler, the parent frame on the call stack is <code>tryCatch()</code> (the handler stack is similarly truncated), and everything higher is discarded. If it is local, the parent frame on the call stack is the one where the error was signaled.</p></li>
<li><p>As a result of (3), when exiting handlers return, execution continues from wherever <code>tryCatch()</code> was called. However, if a local handler returns, the value is discarded and control is given to the next available handler.</p></li>
<li><p>When invoking a local handler, the parent <em>environment</em> is wherever <code>withCallingHandlers()</code> was called, not the environment that signalled the condition.</p></li>
</ol>
</div>
<div id="restarts" class="section level3">
<h3>4. Restarts</h3>
<p>Local error handlers can run restart functions in order to circumvent later handlers.</p>
<pre class="r"><code># list available ones
f &lt;- function () {
  computeRestarts(simpleMessage(&quot;hello&quot;))
}

withRestarts(f(), custom_message = function () NULL)
#&gt; [[1]]
#&gt; &lt;restart: custom_message &gt;
#&gt; 
#&gt; [[2]]
#&gt; &lt;restart: abort &gt;

g &lt;- function () {
  cat(&quot;this executes\n&quot;)
  invokeRestart(&quot;custom&quot;)
  cat(&quot;this doesn&#39;t\n&quot;)
}

f &lt;- function () g()

custom_abort &lt;- function () {
  &quot;aborting, this string gets returned&quot;
}

withRestarts(f(), custom = custom_abort)
#&gt; this executes
#&gt; [1] &quot;aborting, this string gets returned&quot;</code></pre>
</div>
<div id="warning-options" class="section level3">
<h3>5. Warning options</h3>
<p>Warnings can be handled in different ways:</p>
<pre class="r"><code>f &lt;- function () {
    cat(&quot;do this first\n&quot;)
    warning(&quot;&quot;)
    cat(&quot;do this second\n&quot;)
}

g &lt;- function () withCallingHandlers(f(), warning = function (x) {
    cat(&quot;handling the warning\n&quot;)
}, error = function (x) {
    cat(&quot;this is an error!\n&quot;)
    invokeRestart(&quot;abort&quot;)
})

options(warn = 0)
g()
#&gt; do this first
#&gt; handling the warning
#&gt; do this second
#&gt; Warning message:
#&gt; In f() : 

options(warn = 1)
g()
#&gt; do this first
#&gt; handling the warning
#&gt; Warning in f() : 
#&gt; do this second
 
options(warn = 2)
g()
#&gt; do this first
#&gt; handling the warning
#&gt; this is an error!</code></pre>
</div>
